version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"
  webmethods:
    build:
      context: .
      dockerfile: Dockerfile
    image: webmethods:latest